const slugToImage: Record<string, string> = {
  "handelsavtalet": "/Images/sectors/handel.jpg",
  "teknikavtalet": "/Images/sectors/industri.jpg",
  "teknikavtalet-tjansteman": "/Images/sectors/industri.jpg",
  "handelns-tjanstemannaavtal": "/Images/sectors/handel.jpg",
  "byggavtalet": "/Images/sectors/bygg-anlaggning.jpg",
  "byggforetagen-tjanstemannaavtal": "/Images/sectors/bygg-anlaggning.jpg",
  "hok-kommunal": "/Images/sectors/vard-omsorg.jpg",
  "it-avtalet": "/Images/sectors/it-tech.jpg",
  "telekomavtalet": "/Images/sectors/it-tech.jpg",
  "innovationsavtalet": "/Images/sectors/kontor-tjansteman.jpg",
  "grona-avtalet": "/Images/sectors/kontor-tjansteman.jpg",
  "systembolagsavtalet": "/Images/sectors/handel.jpg",
  "transportavtalet": "/Images/sectors/transport.jpg",
  "bussbranschavtalet": "/Images/sectors/transport.jpg",
  "tjanstemannaavtalet-transportforetagen": "/Images/sectors/transport.jpg",
  "tjanstemannaavtalet-motorbranschen": "/Images/sectors/transport.jpg",
  "motorbranschavtalet": "/Images/sectors/transport.jpg",
  "bankavtalet-finansforbundet": "/Images/sectors/kontor-tjansteman.jpg",
  "bankavtalet-saco": "/Images/sectors/kontor-tjansteman.jpg",
  "forsakringsavtalet-forena": "/Images/sectors/kontor-tjansteman.jpg",
  "forsakringsavtalet-saco": "/Images/sectors/kontor-tjansteman.jpg",
  "apoteksavtalet-svensk-handel": "/Images/sectors/kontor-tjansteman.jpg",
  "apoteksforetagen-almega": "/Images/sectors/kontor-tjansteman.jpg",
  "journalistavtalet-dagspress": "/Images/sectors/kontor-tjansteman.jpg",
  "journalistavtalet-public-service": "/Images/sectors/kontor-tjansteman.jpg",
  "journalistavtalet-tidskrift": "/Images/sectors/kontor-tjansteman.jpg",
  "journalistavtalet-etermedier": "/Images/sectors/kontor-tjansteman.jpg",
  "journalistavtalet-bemanning": "/Images/sectors/kontor-tjansteman.jpg",
  "sobona-bok-besoksnaring-kulturarv": "/Images/sectors/hotell-restaurang.jpg",
  "sobona-bok-energi": "/Images/sectors/industri.jpg",
  "sobona-bok-fastigheter": "/Images/sectors/kontor-tjansteman.jpg",
  "sobona-bok-flygplatser": "/Images/sectors/transport.jpg",
  "sobona-bok-vatten-miljo": "/Images/sectors/industri.jpg",
  "friskoleavtalet-larare": "/Images/sectors/skola-utbildning.jpg",
  "friskoleavtalet-kommunal": "/Images/sectors/skola-utbildning.jpg",
  "svenska-kyrkan-tjansteman": "/Images/sectors/kontor-tjansteman.jpg",
  "svenska-kyrkan-kommunal": "/Images/sectors/kontor-tjansteman.jpg",
  "hotell-restaurang": "/Images/sectors/hotell-restaurang.jpg",
  "besoksnaringens-tjanstemannaavtal": "/Images/sectors/hotell-restaurang.jpg",
  "ab-kommunalt": "/Images/sectors/vard-omsorg.jpg",
  "hok-vision": "/Images/sectors/kontor-tjansteman.jpg",
  "villkorsavtal-saco": "/Images/sectors/kontor-tjansteman.jpg",
  "villkorsavtal-ofr": "/Images/sectors/kontor-tjansteman.jpg",
  "villkorsavtal-seko": "/Images/sectors/kontor-tjansteman.jpg",
  "spartrafikavtalet": "/Images/sectors/transport.jpg",
  "branschavtal-kommunikation": "/Images/sectors/transport.jpg",
  "branschavtal-energi-efa": "/Images/sectors/industri.jpg",
  "installationsavtalet": "/Images/sectors/bygg-anlaggning.jpg",
  "bemanningsavtalet": "/Images/sectors/kontor-tjansteman.jpg",
  "kompetensforetagen-tjansteman": "/Images/sectors/kontor-tjansteman.jpg",
  "fastighetsavtalet": "/Images/sectors/kontor-tjansteman.jpg",
  "bevaknings-sakerhetsavtalet": "/Images/sectors/kontor-tjansteman.jpg",
  "fastigheter-arbetare-almega": "/Images/sectors/kontor-tjansteman.jpg",
  "f-avtalet-fastigo": "/Images/sectors/kontor-tjansteman.jpg",
  "skogsavtalet-privat": "/Images/sectors/industri.jpg",
  "sagverksavtalet-industriarbetsgivarna": "/Images/sectors/industri.jpg",
  "sagverksindustrin-tjansteman": "/Images/sectors/industri.jpg",
  "traindustriavtalet-tmf": "/Images/sectors/industri.jpg",
  "traindustrin-tjansteman-tmf": "/Images/sectors/industri.jpg",
  "stal-metallindustrin-tjansteman": "/Images/sectors/industri.jpg",
  "gruvindustrin-tjansteman": "/Images/sectors/industri.jpg",
  "gruvindustrin-if-metall": "/Images/sectors/industri.jpg",
  "massa-pappersindustrin-pappers": "/Images/sectors/industri.jpg",
  "massa-pappersindustrin-tjansteman": "/Images/sectors/industri.jpg",
  "skogsavtalet": "/Images/sectors/industri.jpg",
  "bankavtalet": "/Images/sectors/kontor-tjansteman.jpg",
  "livsmedelsavtalet": "/Images/sectors/industri.jpg",
  "livsmedelsindustrin-tjanstemannaavtal": "/Images/sectors/industri.jpg",
  "ikem-tjanstemannaavtal": "/Images/sectors/industri.jpg",
  "vardforetagarna-bransch-e": "/Images/sectors/vard-omsorg.jpg",
  "vardforetagarna-bransch-f": "/Images/sectors/vard-omsorg.jpg",
  "vardforetagarna-bransch-g": "/Images/sectors/vard-omsorg.jpg",
  "fremia-personlig-assistans": "/Images/sectors/vard-omsorg.jpg",
  "serviceentreprenad-fastighets-seko": "/Images/sectors/kontor-tjansteman.jpg",
  "serviceentreprenad-kommunal": "/Images/sectors/kontor-tjansteman.jpg",
  "laraavtalet": "/Images/sectors/skola-utbildning.jpg",
  "sjukskoterska-avtal": "/Images/sectors/vard-omsorg.jpg",
  "lakare-kommun": "/Images/sectors/vard-omsorg.jpg",
};

const sectorToImage: Record<string, string> = {
  "Privat transport": "/Images/sectors/transport.jpg",
  "Privat motorbransch": "/Images/sectors/transport.jpg",
  "Privat handel": "/Images/sectors/handel.jpg",
  "Privat hotell/restaurang": "/Images/sectors/hotell-restaurang.jpg",
  "Privat industri": "/Images/sectors/industri.jpg",
  "Privat IT/telekom": "/Images/sectors/it-tech.jpg",
  "Privat IT/tech": "/Images/sectors/it-tech.jpg",
  "Privat teknikkonsult": "/Images/sectors/kontor-tjansteman.jpg",
  "Privat tjänstesektor": "/Images/sectors/kontor-tjansteman.jpg",
  "Privat bygg": "/Images/sectors/bygg-anlaggning.jpg",
  "Privat installation": "/Images/sectors/bygg-anlaggning.jpg",
  "Privat bank/finans": "/Images/sectors/kontor-tjansteman.jpg",
  "Privat försäkring": "/Images/sectors/kontor-tjansteman.jpg",
  "Privat apotek": "/Images/sectors/kontor-tjansteman.jpg",
  "Privat media": "/Images/sectors/kontor-tjansteman.jpg",
  "Privat bemanning": "/Images/sectors/kontor-tjansteman.jpg",
  "Privat fastighet": "/Images/sectors/kontor-tjansteman.jpg",
  "Privat bevakning och säkerhet": "/Images/sectors/kontor-tjansteman.jpg",
  "Fastighetsarbete": "/Images/sectors/kontor-tjansteman.jpg",
  "Privat skogsbruk": "/Images/sectors/industri.jpg",
  "Privat sågverksindustri": "/Images/sectors/industri.jpg",
  "Privat träindustri": "/Images/sectors/industri.jpg",
  "Privat massa- och pappersindustri": "/Images/sectors/industri.jpg",
  "Privat vård": "/Images/sectors/vard-omsorg.jpg",
  "Privat vård och omsorg": "/Images/sectors/vard-omsorg.jpg",
  "Privat äldreomsorg": "/Images/sectors/vard-omsorg.jpg",
  "Privat personlig assistans": "/Images/sectors/vard-omsorg.jpg",
  "Privat livsmedelsindustri": "/Images/sectors/industri.jpg",
  "Privat service": "/Images/sectors/kontor-tjansteman.jpg",
  "Privat utbildning": "/Images/sectors/skola-utbildning.jpg",
  "Kommunalt företag": "/Images/sectors/kontor-tjansteman.jpg",
  "Svenska kyrkan": "/Images/sectors/kontor-tjansteman.jpg",
  "Kommun/region": "/Images/sectors/vard-omsorg.jpg",
  "Statlig sektor": "/Images/sectors/kontor-tjansteman.jpg",
  "Statligt skogsbruk": "/Images/sectors/industri.jpg",
};

const categoryToImage: Record<string, string> = {
  "Vård & Omsorg": "/Images/sectors/vard-omsorg.jpg",
  "Skola & Utbildning": "/Images/sectors/skola-utbildning.jpg",
  "Bygg": "/Images/sectors/bygg-anlaggning.jpg",
  "Bygg & Anläggning": "/Images/sectors/bygg-anlaggning.jpg",
  "Handel": "/Images/sectors/handel.jpg",
  "Handel & Service": "/Images/sectors/handel.jpg",
  "Transport": "/Images/sectors/transport.jpg",
  "Transport & Logistik": "/Images/sectors/transport.jpg",
  "Hotell & Restaurang": "/Images/sectors/hotell-restaurang.jpg",
  "IT": "/Images/sectors/it-tech.jpg",
  "IT & Teknik": "/Images/sectors/it-tech.jpg",
  "Industri": "/Images/sectors/industri.jpg",
  "Industri & Tillverkning": "/Images/sectors/industri.jpg",
  "Bank": "/Images/sectors/kontor-tjansteman.jpg",
  "Stat": "/Images/sectors/kontor-tjansteman.jpg",
  "Övriga": "/Images/misc/meeting-room.jpg",
  "Kontor & Administration": "/Images/sectors/kontor-tjansteman.jpg",
  "Bank & Försäkring": "/Images/sectors/kontor-tjansteman.jpg",
};

const DEFAULT_IMAGE = "/Images/misc/meeting-room.jpg";

export function getAgreementHeroImage(slug: string, sectorLabel?: string): string {
  return slugToImage[slug] || (sectorLabel && sectorToImage[sectorLabel]) || DEFAULT_IMAGE;
}

export function getOccupationHeroImage(category: string): string {
  return categoryToImage[category] || DEFAULT_IMAGE;
}
